apiVersion: skaffold/v4beta7
kind: Config
metadata:
  name: feature-pipeline

build:
  local:
    push: false
    useBuildkit: false
  artifacts:
    - image: togather-ml-feature-pipeline
      context: .
      docker:
        dockerfile: Dockerfile
    - image: togather-ml/flink-feature-job
      context: .
      docker:
        dockerfile: docker/Dockerfile.flink
manifests:
  rawYaml:
    - k8s/deployment.yaml
    - k8s/service.yaml
    - k8s/ingress.yaml
deploy:
  kubectl: {}
