apiVersion: v1
kind: Service
metadata:
  name: feature-pipeline
  labels:
    app: feature-pipeline
spec:
  selector:
    app: feature-pipeline
  ports:
    - port: 8000
      targetPort: 8000
  type: ClusterIP
